### ISSUE TITLE
Use an image proxy to resize large images and prevent IP address leakage.

### ISSUE THREAD

**Issue by 6a68** [mozilla/universal-search-recommendation#104]
Not clear if we can reuse the embedly-proxy for this purpose or not, let's look into it.

**Comment by chuckharmston** [comment]
If we need a proxy for Clearbit images, we should invest in a generic proxy, rather than do the work to integrate with the one Activity Stream uses; it doesn't give us anything that we don't otherwise have, and a more generic image proxy would give us everything we need from not just Embedly, but Clearbit, IMDB, and every other image provider we use.

**Comment by chuckharmston** [comment]
One open source option: https://github.com/willnorris/imageproxy
One aaS option: https://www.imgix.com/
