### ISSUE TITLE
Override bad logos

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-recommendation#126]
Some sites do a poor job reporting their logo. We should consider overriding results for specific TLDs where appropriate.

**Comment by chuckharmston** [comment]
![screen shot 2016-05-05 at 8 59 09 pm](https://cloud.githubusercontent.com/assets/23885/15063102/5448b7b6-1304-11e6-9486-413db1374bb4.png)
![screen shot 2016-05-05 at 8 58 58 pm](https://cloud.githubusercontent.com/assets/23885/15063104/566d03da-1304-11e6-9b85-3dcd8ed38bf6.png)

**Comment by chuckharmston** [comment]
![screen shot 2016-05-09 at 10 03 11 am](https://cloud.githubusercontent.com/assets/23885/15119255/4a8269fe-15cd-11e6-87e5-e1f8559645db.png)

**Comment by chuckharmston** [comment]
This would be particularly important if we decide to implement https://github.com/mozilla/universal-search/issues/196

**Comment by chuckharmston** [comment]
<img width="224" alt="screen shot 2016-05-10 at 5 17 16 pm" src="https://cloud.githubusercontent.com/assets/23885/15165459/1c9c2f8c-16d3-11e6-8a89-005c6ffde0c7.png">

(Thanks, @shorlander!)

**Comment by pdehaan** [comment]
You could try using @nchapman's [**tippy-top-sites**](https://github.com/nchapman/tippy-top-sites) repo as some sort of "pre-proxy".
It should have nice images for all these sites above:

| SITE | TIPPY-TOP-ICON | CLEARBIT ICON
|----|----|----|
| netflix.com | ![](https://rawgit.com/nchapman/tippy-top-sites/master/images/netflix-com.png) | ![](http://logo.clearbit.com/netflix.com)
| espn.go.com | ![](https://raw.githubusercontent.com/nchapman/tippy-top-sites/master/images/espn-go-com.png) | ![](http://logo.clearbit.com/espn.go.com)
| allrecipes.com | ![](https://raw.githubusercontent.com/nchapman/tippy-top-sites/master/images/allrecipes-com.png) | ![](http://logo.clearbit.com/allrecipes.com)
| lowes.com | ![](https://raw.githubusercontent.com/nchapman/tippy-top-sites/master/images/lowes-com.png) | ![](http://logo.clearbit.com/www.lowes.com)

You can see a bit of funk on the lowes.com icon because it's transparent w/ white pixels. We also include some background color info in the tippy-top-JSON. Not sure how well this plays w/ Python since we've only tested w/ Node 5, but JSON should be JSON.
