### ISSUE TITLE
Web server creates but does not close redis connections

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/universal-search-recommendation#92]
I got a pagerduty alert. Investigating found that there were thousands of connections open to the redis server:

```bash
> netstat -aln | grep 6379 | wc -l
28232
```

In the logs I see: 

```
...
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 482, in _connect
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: sock.connect(socket_address)
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: OSError: [Errno 99] Cannot assign requested address
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: During handling of the above exception, another exception occurred:
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: Traceback (most recent call last):
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: File "/usr/local/lib/python3.5/site-packages/redis/client.py", line 572, in execute_command
Apr 08 04:01:59 ip-172-31-3-146 docker[2782]: connection.send_command(*args)
...
```

The important line in the log is: `OSError: [Errno 99] Cannot assign requested address`

This is a OS / kernel error that comes up when no more connections to an IP can be made. Most likely this is the result of the `__heartbeat__` endpoint being monitored and it opens but doesn't close connections to redis.

**Comment by chuckharmston** [comment]
We never make direct connections to redis or even interact with it at all from our application; for the heartbeat view we [ping Celery](https://github.com/mozilla/universal-search-recommendation/blob/d8f0bd13ceb21bf03463969b58f88d509f4096e8/recommendation/views/status.py#L37-L47), which will raise a `RedisConnectionError` if Redis is down.

I don't think that's where the bug is.

**Comment by chuckharmston** [comment]
In fact, the only reason we require the redis library at all is because Celery doesn't guarantee that [redis' `ConnectionError` is available to import](https://github.com/celery/celery/blob/354cab91bc28e5014923aeaa83424891ae4dec72/celery/backends/redis.py#L29-L36) and catch.

**Comment by chuckharmston** [comment]
Some ideas:

- Celery's [`BROKER_POOL_LIMIT`](http://celery.readthedocs.org/en/latest/configuration.html#broker-pool-limit) setting.
- Celery's [`CELERY_REDIS_MAX_CONNECTIONS`](http://celery.readthedocs.org/en/latest/configuration.html#celery-redis-max-connections) setting.
- Set a Redis [client timeout](http://redis.io/topics/clients#client-timeouts). This seems like a nuclear option, but it probably gets the job done.

**Comment by mostlygeek** [comment]
Are those celery options configurable via environment variables? conf.py doesn't seem to set anything in python for controlling celery. 

The docs say the default size of BROKER_POOL_LIMIT is 10. There were 28232 connections open to the redis server when it failed. I'm not 100% sure it is the __heartbeat__ check that is actually creating the connections. 

How would a live endpoint be tested? Any functional tests available?

**Comment by chuckharmston** [comment]
The Celery options are applied by adding a `celeryconfig` module somewhere in the `$PYTHONPATH`. Let me know which ones you'd like to work with, and I can add one that pulls from an environment variable.

If you want to mess with it locally, our local instructions should be fine: https://github.com/mozilla/universal-search-recommendation/blob/master/docs/local.md

**Comment by mostlygeek** [comment]
I also tested this with redis on localhost and the same problem occurs. The number of open connections continues to grow.

**Comment by chuckharmston** [comment]
@mostlygeek Are you open to the idea of the application server being able to communicate directly with Redis? Per the dockerflow spec we have to ping it for heartbeat, but clearly there's a problem in the means by which Celery lets us check on the broker's status.

**Comment by mostlygeek** [comment]
i have no problems with the app talking directly to redis.

**Comment by 6a68** [comment]
I think we might want to explore other configuration changes before trying to land any workaround patches.

Based on looking through the celery github issue tracker, many connection pooling problems / deadlocks seem to be solved by adjusting configuration values: either disabling connection pooling, by setting `BROKER_POOL_LIMIT=0`, or disabling task prefetching, by passing the `-Ofair` option.

[Here](https://github.com/celery/celery/issues/2991) is a Celery connection pooling bug that affected RabbitMQ--the problems aren't confined to Celery + Redis. It was reportedly solved by setting `BROKER_POOL_LIMIT=0`, see docs [here](http://docs.celeryproject.org/en/latest/configuration.html#std:setting-BROKER_POOL_LIMIT).

[Here](https://github.com/celery/celery/issues/2464) is a similar Celery-Redis deadlock bug, reportedly fixed by disabling "prefetch" behavior in the workers. Passing the `-Ofair` option at the command line is discussed in the docs [here](http://celery.readthedocs.org/en/latest/userguide/optimizing.html#prefork-pool-prefetch-settings).
